# Generated by Django 4.2.5 on 2023-09-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='items_price',
            new_name='item_price',
        ),
    ]
